const express = require('express')
const app = express()
const port = 3000
const fs = require('fs');


app.get('/', (req, res) => {


let rawdata = fs.readFileSync('frases.json');
let frases = JSON.parse(rawdata);
console.log(frases);
  res.send([
{"frases":"…he hecho una cubana o viceversa.","id":"1"},
{"frases":"…he utilizado condones de sabores.","id":"2"},
{"frases":"…he practicado sexo con un\/a negro\/a.","id":"3"},
{"frases":"…he practicado sexo con un\/a asiático\/a.","id":"4"},
{"frases":"…he practicado sexo con un\/a italiano\/a.","id":"5"},
{"frases":"…he practicado sexo con una persona que no fuera española.","id":"6"},
{"frases":"…he practicado sexo con un\/a alemán\/a.","id":"7"},
{"frases":"…he practicado sexo con una persona con un pene o unas tetas enormes.","id":"8"},
{"frases":"…he practicado sexo con una persona con un pene o unas tetas muy pequeñas.","id":"9"},
{"frases":"…pagaría 100€ por tener sexo con alguien de este grupo.","id":"10"},
{"frases":"…tendría sexo con la persona de mi izquierda.","id":"11"},
{"frases":"…tendría sexo con la persona de mi derecha.","id":"12"},
{"frases":"…me desnudaría completamente delante de este grupo para ganar 50€.","id":"13"},
{"frases":"…me suele gustar que me den besos en el cuello.","id":"14"},
{"frases":"…me suele gustar que me den besos en el abdomen.","id":"15"},
{"frases":"…me suele gustar que me den azotes en la cama.","id":"16"},
{"frases":"…me gustaría hacer un trío con mi pareja y otro de sus familiares.","id":"17"},
{"frases":"…haría una película porno para ganar 1.000€.","id":"18"},
{"frases":"…dejaría que me metieran un objeto grande por el culo para ganar 3.000€.","id":"19"},
{"frases":"…he practicado sexo con un\/a sudamericano\/a","id":"20"},
{"frases":"…he roto un condón practicando sexo hasta el final.","id":"21"},
{"frases":"…he practicado sexo con un\/a europeo\/a","id":"22"},
{"frases":"…practicaría sexo con un\/a desconocido\/a.","id":"23"},
{"frases":"…practicaría sexo con un\/a desconocido\/a sin protección.","id":"24"},
{"frases":"…pondría los cuernos a mi pareja.","id":"25"},
{"frases":"…me he masturbado con un objeto.","id":"26"},
{"frases":"…dejaría que me subastaran para realizar sexo conmigo.","id":"27"},
{"frases":"…tendría una relación abierta con mi pareja.","id":"28"},
{"frases":"…practicaría sexo con mi pareja y otra persona de mi mismo sexo.","id":"29"},
{"frases":"…practicaría sexo con mi pareja y otra persona de mi sexo opuesto.","id":"30"},
{"frases":"…practicaría sexo en un intercambio de parejas.","id":"31"},
{"frases":"…me masturbaría desnudo en la plaza de mi pueblo o ciudad de día para ganar 100.000€.","id":"32"},
{"frases":"...me pasaría un hielo con la boca con la persona de mi izquierda.","id":"33"},
{"frases":"…tendría relaciones sexuales con mi hermano\/a para ganar 1.000.000€.","id":"34"},
{"frases":"…tendría relaciones sexuales con mi primo\/a para ganar 100.000€.","id":"35"},
{"frases":"…he utilizado nata","id":"36"},
{"frases":"…he practicado sexo en la arena de la playa.","id":"37"},
{"frases":"…he practicado sexo en el mar.","id":"38"},
{"frases":"…he practicado sexo en una ducha o bañera.","id":"39"},
{"frases":"…he sido sorprendido por mis padres masturbandome.","id":"40"},
{"frases":"…he sido sorprendido por mis padres practicando sexo.","id":"41"},
{"frases":"…he practicado sexo en el trabajo o universidad.","id":"42"},
{"frases":"…me he masturbado en el trabajo o universidad.","id":"43"},
{"frases":"…me he masturbado a solas","id":"44"},
{"frases":"…me he masturbado a solas","id":"45"},
{"frases":"…he practicado sexo","id":"46"},
{"frases":"...le daría un pico a la persona de mi izquierda.","id":"47"},
{"frases":"…suelo preferir el culo a las tetas\/pene.","id":"48"},
{"frases":"…suelo sentirme más atraído por unos ojos bonitos que por una boca bonita.","id":"49"},
{"frases":"…suelo preferir la postura del perrito a la del misionero.","id":"50"},
{"frases":"…practicaría sexo con un caballo para ganar 10.000€.","id":"51"},
{"frases":"…practicaría sexo con un perro para ganar 10.000€.","id":"52"},
{"frases":"...he eyaculado en el pelo o viceversa.","id":"53"},
{"frases":"…he eyaculado en las tetas o viceversa.","id":"54"},
{"frases":"…he eyaculado en el culo o viceversa.","id":"55"},
{"frases":"…he eyaculado en la cara o viceversa.","id":"56"},
{"frases":"…me he masturbado pensando en un amigo\/a.","id":"57"},
{"frases":"…he practicado sexo anal hasta el final sin protección.","id":"58"},
{"frases":"…he practicado sexo anal y he encontrado petróleo.","id":"59"},
{"frases":"…he recibido un pedo en la cara practicado sexo oral o viceversa.","id":"60"},
{"frases":"…suelo disfrutar cuando me meten un dedo por el ano.","id":"61"},
{"frases":"…suelo borrar el historial después de ver porno.","id":"62"},
{"frases":"…tendría relaciones sexuales con un gordo\/a.","id":"63"},
{"frases":"…practicaría sexo sadomasoquista.","id":"64"},
{"frases":"…haría una orgía con este grupo hoy mismo.","id":"65"},
{"frases":"…tendría relaciones sexuales con alguien de este grupo hoy mismo.","id":"66"},
{"frases":"…tendría de follamigo\/a a alguien de este grupo.","id":"67"},
{"frases":"…me he sentido atraído sexualmente por alguien de este grupo.","id":"68"},
{"frases":"…le comería la boca a alguien de este grupo.","id":"69"},
{"frases":"…me he sentido atraído sexualmente por el culo de alguien de este grupo.","id":"70"},
{"frases":"…he pensado que alguien de este grupo tuviera un pene enorme.","id":"71"},
{"frases":"…me he sentido atraído sexualmente por las tetas o abdomen de alguien de este grupo.","id":"72"},
{"frases":"…he pensado que alguien de este grupo es muy guapo\/a.","id":"73"},
{"frases":"…he pensado que alguien de este grupo tiene un cuerpo sexy.","id":"74"},
{"frases":"…me he imaginado desnudo a alguien de este grupo.","id":"75"},
{"frases":"…he tenido un sueño erótico con alguien de este grupo.","id":"76"},
{"frases":"…he tenido relaciones sexuales gracias a Tinder.","id":"77"},
{"frases":"…he pensado que alguien de este grupo tiene unos ojazos.","id":"78"},
{"frases":"…he pensado que alguien de este grupo tiene unos labios sexys.","id":"79"},
{"frases":"…me he sentido atraído sexualmente por la mirada de alguien de este grupo.","id":"80"},
{"frases":"…he tenido relaciones sexuales en un cine.","id":"81"},
{"frases":"…he tenido relaciones sexuales en un tren.","id":"82"},
{"frases":"…he tenido relaciones sexuales en un autobus.","id":"83"},
{"frases":"…he tenido relaciones sexuales en un coche en marcha.","id":"84"},
{"frases":"…he tenido relaciones sexuales en una discoteca.","id":"85"},
{"frases":"…he tenido relaciones sexuales en la calle.","id":"86"},
{"frases":"…he tenido relaciones sexuales en una piscina pública.","id":"87"},
{"frases":"…he tenido relaciones sexuales en presencia de otras personas.","id":"88"},
{"frases":"…he tenido relaciones sexuales en un hospital.","id":"89"},
{"frases":"…he tenido relaciones sexuales en unos provadores.","id":"90"},
{"frases":"…he tenido relaciones sexuales en el suelo.","id":"91"},
{"frases":"…me he caído intentado hacer una postura sexual complicada.","id":"92"},
{"frases":"…suelo preferir hacer el amor lentamente al sexo duro.","id":"93"},
{"frases":"…suelo utilizar preservativo al practicar sexo con desconocidos.","id":"94"},
{"frases":"…suelo practicar sexo con preservativo.","id":"95"},
{"frases":"…he estado más de 1 año sin practicar sexo tras la primera vez.","id":"96"},
{"frases":"…suelo masturbarme a menudo.","id":"97"},
{"frases":"…me gustaría masturbar a alguien de este grupo hoy mismo.","id":"98"},
{"frases":"…me gustaría practicarle sexo oral a alguien de este grupo hoy mismo.","id":"99"},
{"frases":"…he masturbado a alguien con los pies o viceversa.","id":"100"},
{"frases":"…he puesto a alguien muy cachondo\/a con la intención de no terminar la faena.","id":"101"},
{"frases":"…dejaría de practicar sexo de por vida para ganar 10.000.000€.","id":"102"},
{"frases":"…dejaría de masturbarme de por vida para ganar 1.000.000€.","id":"103"},
{"frases":"…me quitaría mis genitales para ganar 1.000.000.000€.","id":"104"},
{"frases":"…moriría para salvaros la vida a todos vosotros\/as.","id":"105"},
{"frases":"…suelo practicar sexo más de 5 veces por semana.","id":"106"},
{"frases":"…suelo utilizar instrumentos para masturbarme.","id":"107"},
{"frases":"…participaría en un bukkake.","id":"108"},
{"frases":"…participaría en un gangbang.","id":"109"},
{"frases":"…he tenido depilados los genitales completamente ahora mismo.","id":"110"},
{"frases":"…me he masturbado discretamente en público.","id":"111"},
{"frases":"…le he negado a mi pareja experimentar algo nuevo en el sexo.","id":"112"},
{"frases":"…suelo proponer nuevas experiencias sexuales a mi pareja.","id":"113"},
{"frases":"…suelo preferir tomar la iniciativa en el sexo.","id":"114"},
{"frases":"…suelo preferir complacer a mi pareja antes que a mi.","id":"115"},
{"frases":"…suelo obedecer en todo lo que me propone mi pareja en el sexo.","id":"116"},
{"frases":"…tendría relaciones sexuales con 10 personas a la vez que me atrayeran sexualmente.","id":"117"},
{"frases":"…suelo practicar sexo con la misma postura por costumbre.","id":"118"},
{"frases":"…suelo empezar las relaciones sexuales con 15 minutos de preliminares o más.","id":"119"},
{"frases":"…suelo practicar sexo oral como calentamiento antes del sexo de penetración.","id":"120"},
{"frases":"…suelo ponerme muy cachondo cuando bebo.","id":"121"},
{"frases":"…suelo disfrutar más del sexo cuando fumo marihuana.","id":"122"},
{"frases":"…suelo preferir un sexo oral de calidad a un sexo de penetración de calidad.","id":"123"},
{"frases":"…suelo preferir practicar sexo recien levantado al sexo por la noche.","id":"124"},
{"frases":"…suelo quedarme dormido después de practicar sexo.","id":"125"},
{"frases":"…suelo hablar de sexo sin tabús con cualquier persona.","id":"126"},
{"frases":"…he llevado a cabo todas mis fantasías sexuales.","id":"127"},
{"frases":"…he satisfecho todos las fantasías sexuales de mi pareja o expareja.","id":"128"},
{"frases":"…he tomado algo afrodisiaco para mejorar mis relaciones sexuales.","id":"129"},
{"frases":"…he practicado sexo con los ojos vendados.","id":"130"},
{"frases":"…suelo ver porno para masturbarme.","id":"131"},
{"frases":"…suelo decirle frases guarras durante el sexo.","id":"132"},
{"frases":"…he utilizado hielo practicando sexo.","id":"133"},
{"frases":"…probaría a tener relaciones sexuales con alguien del mismo sexo.","id":"134"},
{"frases":"…suelo tener reparo en desnudarme completamente al tener relaciones sexuales.","id":"135"},
{"frases":"…perdonaría a mi pareja si se enrollara con otra persona.","id":"136"},
{"frases":"…me he disfrazado para practicar sexo.","id":"137"},
{"frases":"…suelo preferir una cara bonita a un cuerpo sexy.","id":"138"},
{"frases":"…iría a un terapeuta sexual para solucionar un problema con mi pareja.","id":"139"},
{"frases":"…he sabido todas las fantasías sexuales de mi pareja.","id":"140"},
{"frases":"…suelo negarme a tener relaciones sexuales.","id":"141"},
{"frases":"…he terminado una pelicula porno entera.","id":"142"},
{"frases":"…suelo ser exigente con el físico de la persona con la que voy a tener sexo.","id":"143"},
{"frases":"…suelo ser considerado\/a muy experto\/a en el sexo oral.","id":"144"},
{"frases":"…suelo ser considerado\/a muy experto\/a practicando sexo de penetración.","id":"145"},
{"frases":"...he estado más de un mes sin mantener relaciones sexuales con mi pareja.","id":"146"},
{"frases":"…he tenido una experiencia muy mala practicando sexo.","id":"147"},
{"frases":"…suelo considerar muy importante el sexo en una relacion.","id":"148"},
{"frases":"…he tenido un actor o actriz porno favorito\/a.","id":"149"},
{"frases":"…suelo tener éxito al utilizar apps para ligar.","id":"150"},
{"frases":"…me agrandaría o me reduciría alguna parte de mi cuerpo.","id":"151"},
{"frases":"…he tenido un sueño erótico con un\/a famoso\/a","id":"152"},
{"frases":"…he perdido la virginidad con más de 18 años.","id":"153"},
{"frases":"…he sorprendido a mis padres o algún hermano\/a practicando sexo.","id":"154"},
{"frases":"…he fantaseado con alguna persona del mismo sexo.","id":"155"},
{"frases":"…he tenido relaciones sexuales con más de 20 personas.","id":"156"},
{"frases":"...le pasaría mi mano desde el tobillo hasta la ingle a la persona de mi izquierda.","id":"157"},
{"frases":"…he tenido un sueño erótico con alguien que no me gustara.","id":"158"},
{"frases":"...le pasaría mi mano desde el tobillo hasta la ingle a la persona de mi derecha.","id":"159"},
{"frases":"…he tenido relaciones sexuales con más de 3 personas diferentes en un día.","id":"160"},
{"frases":"…he tenido relaciones sexuales con la expareja de un amigo\/a.","id":"161"},
{"frases":"…suele gustarme tener relaciones sexuales en el sofá.","id":"162"},
{"frases":"…he pillado a un amigo\/a practicando sexo.","id":"163"},
{"frases":"…he practicado sexo en una moto.","id":"164"},
{"frases":"…me he sentido atraído sexualmente por un profesor\/a.","id":"165"},
{"frases":"…me he sentido atraído por la pareja de un amigo\/a.","id":"166"},
{"frases":"…me he sentido atraído por un\/a compañero\/a de trabajo.","id":"167"},
{"frases":"…me he hecho una foto practicando sexo.","id":"168"},
{"frases":"…me he masturbado fuera de casa.","id":"169"},
{"frases":"…me he sentido atraído sexualmente por una persona de más de 60 años.","id":"170"},
{"frases":"…he vomitado mientras practicaba sexo o viceversa.","id":"171"},
{"frases":"…he enviado un mensaje erótico a la persona equivocada.","id":"172"},
{"frases":"…he sido sorprendido desnudo por alguien sin quererlo.","id":"173"},
{"frases":"…he tenido relaciones sexuales con alguien con pareja.","id":"174"},
{"frases":"…he practicado sexo con una expareja.","id":"175"},
{"frases":"…he roto la cama practicando sexo.","id":"176"},
{"frases":"…he probado más de 5 posturas durante el sexo.","id":"177"},
{"frases":"…he jugado a ser otra persona practicando sexo.","id":"178"},
{"frases":"…he nombrado a otra persona por error al practicar sexo.","id":"179"},
{"frases":"…he tenido relaciones sexuales con una persona sin conocer su nombre.","id":"180"},
{"frases":"…he visto porno con mi pareja.","id":"181"},
{"frases":"…he practicado sexo en la cama de mis padres.","id":"182"},
{"frases":"…he ligado con otra persona teniendo pareja.","id":"183"},
{"frases":"…he fingido dormir para no tener sexo.","id":"184"},
{"frases":"…he tenido un fetiche extraño.","id":"185"},
{"frases":"…he llegado al orgasmo con el sexo oral.","id":"186"},
{"frases":"…he practicado sexo en la cocina.","id":"187"},
{"frases":"…practicaría sexo con un casado\/a en su propia casa.","id":"188"},
{"frases":"…he practicado sexo durante más de 6 horas seguidas.","id":"189"},
{"frases":"…me he masturbado durante más de 6 horas seguidas.","id":"190"},
{"frases":"…suelo utilizar un tanga sexy a diario.","id":"191"},
{"frases":"…suelo tragarme el semen cuando realizo sexo oral o viceversa.","id":"192"},
{"frases":"…he estado en una cama con más de 1 persona desnuda completamente.","id":"193"},
{"frases":"…suelo ponerme cachondo\/a cuando alguien me come la oreja suavemente.","id":"194"},
{"frases":"…me quitaría una prenda cada vez que fallo en este juego.","id":"195"},
{"frases":"…me he dormido mientras practicaba sexo.","id":"196"},
{"frases":"…he llegado al orgasmo en menos de 2 minutos.","id":"197"},
{"frases":"…he comprado algo en un sexshop.","id":"198"},
{"frases":"…suelo utilizar lubricante cuando me masturbo.","id":"199"},
{"frases":"…suelo ponerme cachondo\/a cuando practico sexo anal.","id":"200"},
{"frases":"…me he masturbado hablando por teléfono sin que la otra persona lo supiera.","id":"201"},
{"frases":"…he practicado sexo con una persona 20 años mayor.","id":"202"},
{"frases":"…he practicado sexo con una persona 20 años menor.","id":"203"},
{"frases":"…he practicado sexo siguiendo el kamasutra.","id":"204"},
{"frases":"…he roto un mueble practicando sexo.","id":"205"},
{"frases":"…he tenido relaciones sexuales delante de un espejo.","id":"206"},
{"frases":"…he tenido un sueño erótico que no he contado a mi pareja.","id":"207"},
{"frases":"…suelo entender que mi pareja se masturbe.","id":"208"},
{"frases":"…entendería que mi pareja se masturbe viendo porno.","id":"209"},
{"frases":"…entendería que mi pareja se masturbara con fotos de conocidos\/as.","id":"210"},
{"frases":"…le daría un beso en el culo a la persona de mi izquierda.","id":"211"},
{"frases":"…he mentido sobre mi edad para practicar sexo.","id":"212"},
{"frases":"…me he puesto cachondo\/a leyendo un libro.","id":"213"},
{"frases":"…he practicado sexo en un ascensor.","id":"214"},
{"frases":"…he estado con una pareja más abierta que yo respecto al sexo.","id":"215"},
{"frases":"…he contado a mi pareja experiencias sexuales con mis exparejas.","id":"216"},
{"frases":"…he practicado sexo una sola vez con un desconocido\/a que no he vuelto a ver.","id":"217"},
{"frases":"…he medido mi pene o mis tetas.","id":"218"},
{"frases":"…he enseñado mis partes íntimas a un amigo\/a del sexo opuesto o viceversa.","id":"219"},
{"frases":"…he tenido un tatuaje en una zona íntima.","id":"220"},
{"frases":"…he hablado abiertamente de mi masturbación con mi pareja.","id":"221"},
{"frases":"…me he masturbado más de 50 veces con el mismo video porno.","id":"222"},
{"frases":"…he pillado a mis hermanos\/as practicando sexo.","id":"223"},
{"frases":"…he tenido relaciones sexuales con mi mascota mirando.","id":"224"},
{"frases":"...he cortado con mi pareja para estar con otra persona.","id":"225"},
{"frases":"...he tenido una categoría porno favorita.","id":"226"},
{"frases":"...he odiado una postura sexual","id":"227"},
{"frases":"...perrearía con la persona de mi izquierda.","id":"228"},
{"frases":"...le daría un beso al paquete de la persona de mi derecha.","id":"229"},
{"frases":"...le daría un pico a la persona de mi derecha.","id":"230"},
{"frases":"...le comería la oreja a la persona de mi izquierda.","id":"231"}])

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
